# nixpacks.toml

[phases.setup]
# We must list EVERYTHING we need, because manual config overrides auto-detection.
# 'nodejs' and 'npm' are required to run your backend.
nixPkgs = ["nodejs", "npm", "qpdf"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "npm start"